struct libspotify
{
  void *handle;
  sp_track * (*sp_playlist_track)(sp_playlist *, int);
  sp_artistbrowse * (*sp_artistbrowse_create)(sp_session *, sp_artist *, sp_artistbrowse_type, artistbrowse_complete_cb *, void *);
  const char * (*sp_user_canonical_name)(sp_user *);
  const char * (*sp_albumbrowse_review)(sp_albumbrowse *);
  sp_error (*sp_session_set_connection_type)(sp_session *, sp_connection_type);
  bool (*sp_playlist_track_seen)(sp_playlist *, int);
  sp_error (*sp_user_release)(sp_user *);
  bool (*sp_offline_sync_get_status)(sp_session *, sp_offline_sync_status *);
  int (*sp_toplistbrowse_backend_request_duration)(sp_toplistbrowse *);
  sp_track_offline_status (*sp_track_offline_get_status)(sp_track *);
  sp_playlistcontainer * (*sp_session_publishedcontainer_for_user_create)(sp_session *, const char *);
  bool (*sp_search_is_loaded)(sp_search *);
  sp_error (*sp_session_forget_me)(sp_session *);
  sp_artist * (*sp_link_as_artist)(sp_link *);
  sp_error (*sp_session_set_cache_size)(sp_session *, size_t);
  int (*sp_playlist_track_create_time)(sp_playlist *, int);
  int (*sp_search_num_playlists)(sp_search *);
  sp_error (*sp_session_process_events)(sp_session *, int *);
  sp_error (*sp_session_preferred_bitrate)(sp_session *, sp_bitrate);
  sp_artist * (*sp_artistbrowse_artist)(sp_artistbrowse *);
  sp_image * (*sp_image_create)(sp_session *, const byte);
  sp_error (*sp_playlistcontainer_add_ref)(sp_playlistcontainer *);
  sp_error (*sp_search_release)(sp_search *);
  sp_error (*sp_playlistcontainer_release)(sp_playlistcontainer *);
  sp_albumbrowse * (*sp_albumbrowse_create)(sp_session *, sp_album *, albumbrowse_complete_cb *, void *);
  sp_error (*sp_session_logout)(sp_session *);
  sp_error (*sp_playlist_remove_tracks)(sp_playlist *, const int *, int);
  bool (*sp_playlistcontainer_is_loaded)(sp_playlistcontainer *);
  sp_error (*sp_session_is_scrobbling_possible)(sp_session *, sp_social_provider, bool*);
  sp_error (*sp_artistbrowse_error)(sp_artistbrowse *);
  bool (*sp_toplistbrowse_is_loaded)(sp_toplistbrowse *);
  sp_error (*sp_image_remove_load_callback)(sp_image *, image_loaded_cb *, void *);
  int (*sp_link_as_string)(sp_link *, char *, int);
  sp_error (*sp_playlist_add_tracks)(sp_playlist *, sp_track *const*, int, int, sp_session *);
  bool (*sp_playlist_is_in_ram)(sp_session *, sp_playlist *);
  const char * (*sp_artistbrowse_biography)(sp_artistbrowse *);
  const char* (*sp_error_message)(sp_error);
  sp_error (*sp_session_set_scrobbling)(sp_session *, sp_social_provider, sp_scrobbling_state);
  const char * (*sp_playlist_get_description)(sp_playlist *);
  const char * (*sp_album_name)(sp_album *);
  int (*sp_search_total_albums)(sp_search *);
  sp_artist * (*sp_albumbrowse_artist)(sp_albumbrowse *);
  sp_playlist * (*sp_session_starred_for_user_create)(sp_session *, const char *);
  int (*sp_albumbrowse_num_copyrights)(sp_albumbrowse *);
  sp_link * (*sp_link_create_from_artistbrowse_portrait)(sp_artistbrowse *, int);
  sp_error (*sp_link_add_ref)(sp_link *);
  sp_error (*sp_session_login)(sp_session *, const char *, const char *, bool, const char *);
  sp_error (*sp_toplistbrowse_error)(sp_toplistbrowse *);
  sp_error (*sp_track_error)(sp_track *);
  sp_error (*sp_playlist_add_callbacks)(sp_playlist *, sp_playlist_callbacks *, void *);
  const char * (*sp_search_playlist_uri)(sp_search *, int);
  sp_error (*sp_session_player_load)(sp_session *, sp_track *);
  sp_playlist * (*sp_session_starred_create)(sp_session *);
  bool (*sp_user_is_loaded)(sp_user *);
  sp_track_availability (*sp_track_get_availability)(sp_session *, sp_track *);
  sp_error (*sp_session_player_unload)(sp_session *);
  sp_search * (*sp_search_create)(sp_session *, const char *, int, int, int, int, int, int, int, int, sp_search_type, search_complete_cb *, void *);
  const char * (*sp_session_user_name)(sp_session *);
  sp_error (*sp_playlist_set_autolink_tracks)(sp_playlist *, bool);
  sp_link * (*sp_link_create_from_search)(sp_search *);
  sp_error (*sp_session_preferred_offline_bitrate)(sp_session *, sp_bitrate, bool);
  sp_error (*sp_playlistcontainer_playlist_folder_name)(sp_playlistcontainer *, int, char *, int);
  sp_album * (*sp_albumbrowse_album)(sp_albumbrowse *);
  sp_track * (*sp_toplistbrowse_track)(sp_toplistbrowse *, int);
  bool (*sp_session_get_volume_normalization)(sp_session *);
  int (*sp_search_num_tracks)(sp_search *);
  int (*sp_playlistcontainer_get_unseen_tracks)(sp_playlistcontainer *, sp_playlist *, sp_track **, int);
  const byte * (*sp_artistbrowse_portrait)(sp_artistbrowse *, int);
  int (*sp_search_total_tracks)(sp_search *);
  sp_error (*sp_artistbrowse_add_ref)(sp_artistbrowse *);
  sp_error (*sp_search_add_ref)(sp_search *);
  sp_error (*sp_search_error)(sp_search *);
  sp_error (*sp_toplistbrowse_release)(sp_toplistbrowse *);
  sp_artist * (*sp_toplistbrowse_artist)(sp_toplistbrowse *, int);
  sp_error (*sp_image_add_ref)(sp_image *);
  sp_error (*sp_playlist_update_subscribers)(sp_session *, sp_playlist *);
  sp_playlist_type (*sp_playlistcontainer_playlist_type)(sp_playlistcontainer *, int);
  int (*sp_toplistbrowse_num_albums)(sp_toplistbrowse *);
  sp_error (*sp_session_flush_caches)(sp_session *);
  sp_error (*sp_playlist_track_set_seen)(sp_playlist *, int, bool);
  sp_error (*sp_image_error)(sp_image *);
  sp_error (*sp_image_release)(sp_image *);
  sp_playlist * (*sp_playlist_create)(sp_session *, sp_link *);
  sp_playlist_offline_status (*sp_playlist_get_offline_status)(sp_session *, sp_playlist *);
  int (*sp_artistbrowse_num_portraits)(sp_artistbrowse *);
  sp_playlist * (*sp_search_playlist)(sp_search *, int);
  int (*sp_track_popularity)(sp_track *);
  sp_error (*sp_inbox_release)(sp_inbox *);
  sp_user * (*sp_session_user)(sp_session *);
  sp_error (*sp_albumbrowse_error)(sp_albumbrowse *);
  sp_error (*sp_inbox_error)(sp_inbox *);
  sp_track * (*sp_artistbrowse_track)(sp_artistbrowse *, int);
  sp_error (*sp_albumbrowse_add_ref)(sp_albumbrowse *);
  sp_user * (*sp_playlistcontainer_owner)(sp_playlistcontainer *);
  bool (*sp_album_is_available)(sp_album *);
  int (*sp_toplistbrowse_num_artists)(sp_toplistbrowse *);
  void * (*sp_session_userdata)(sp_session *);
  sp_error (*sp_albumbrowse_release)(sp_albumbrowse *);
  int (*sp_toplistbrowse_num_tracks)(sp_toplistbrowse *);
  sp_user * (*sp_playlist_owner)(sp_playlist *);
  sp_inbox * (*sp_inbox_post_tracks)(sp_session *, const char *, sp_track * const *, int, const char *, inboxpost_complete_cb *, void *);
  sp_uint64 (*sp_playlistcontainer_playlist_folder_id)(sp_playlistcontainer *, int);
  sp_error (*sp_track_add_ref)(sp_track *);
  sp_link * (*sp_link_create_from_user)(sp_user *);
  bool (*sp_playlist_is_collaborative)(sp_playlist *);
  sp_imageformat (*sp_image_format)(sp_image *);
  int (*sp_search_num_artists)(sp_search *);
  const void * (*sp_image_data)(sp_image *, size_t *);
  sp_track * (*sp_localtrack_create)(const char *, const char *, const char *, int);
  const char * (*sp_albumbrowse_copyright)(sp_albumbrowse *, int);
  sp_album * (*sp_search_album)(sp_search *, int);
  sp_error (*sp_session_set_connection_rules)(sp_session *, sp_connection_rules);
  int (*sp_offline_num_playlists)(sp_session *);
  sp_album * (*sp_track_album)(sp_track *);
  const char * (*sp_track_name)(sp_track *);
  int (*sp_search_total_playlists)(sp_search *);
  sp_error (*sp_playlist_reorder_tracks)(sp_playlist *, const int *, int, int);
  sp_error (*sp_session_set_volume_normalization)(sp_session *, bool);
  sp_error (*sp_track_set_starred)(sp_session *, sp_track *const*, int, bool);
  bool (*sp_artist_is_loaded)(sp_artist *);
  sp_track * (*sp_albumbrowse_track)(sp_albumbrowse *, int);
  sp_track * (*sp_link_as_track_and_offset)(sp_link *, int *);
  sp_artist * (*sp_artistbrowse_similar_artist)(sp_artistbrowse *, int);
  sp_connectionstate (*sp_session_connectionstate)(sp_session *);
  int (*sp_playlist_get_offline_download_completed)(sp_session *, sp_playlist *);
  sp_error (*sp_playlist_remove_callbacks)(sp_playlist *, sp_playlist_callbacks *, void *);
  bool (*sp_image_is_loaded)(sp_image *);
  sp_error (*sp_playlistcontainer_remove_callbacks)(sp_playlistcontainer *, sp_playlistcontainer_callbacks *, void *);
  int (*sp_albumbrowse_backend_request_duration)(sp_albumbrowse *);
  sp_error (*sp_playlist_subscribers_free)(sp_subscribers *);
  const char * (*sp_search_playlist_image_uri)(sp_search *, int);
  sp_artist * (*sp_track_artist)(sp_track *, int);
  bool (*sp_session_is_private_session)(sp_session *);
  int (*sp_albumbrowse_num_tracks)(sp_albumbrowse *);
  int (*sp_session_remembered_user)(sp_session *, char *, size_t);
  unsigned int (*sp_playlist_num_subscribers)(sp_playlist *);
  const char * (*sp_user_display_name)(sp_user *);
  sp_error (*sp_toplistbrowse_add_ref)(sp_toplistbrowse *);
  bool (*sp_playlist_is_loaded)(sp_playlist *);
  bool (*sp_playlist_get_image)(sp_playlist *, byte);
  sp_image * (*sp_image_create_from_link)(sp_session *, sp_link *);
  int (*sp_album_year)(sp_album *);
  sp_track * (*sp_search_track)(sp_search *, int);
  bool (*sp_albumbrowse_is_loaded)(sp_albumbrowse *);
  sp_link * (*sp_link_create_from_artist_portrait)(sp_artist *, sp_image_size);
  sp_artist * (*sp_album_artist)(sp_album *);
  int (*sp_offline_tracks_to_sync)(sp_session *);
  sp_error (*sp_session_player_prefetch)(sp_session *, sp_track *);
  sp_error (*sp_playlist_rename)(sp_playlist *, const char *);
  sp_error (*sp_artist_release)(sp_artist *);
  const char * (*sp_artist_name)(sp_artist *);
  bool (*sp_playlist_has_pending_changes)(sp_playlist *);
  bool (*sp_track_is_local)(sp_session *, sp_track *);
  bool (*sp_album_is_loaded)(sp_album *);
  sp_link * (*sp_link_create_from_album_cover)(sp_album *, sp_image_size);
  const char * (*sp_search_did_you_mean)(sp_search *);
  const byte * (*sp_artist_portrait)(sp_artist *, sp_image_size);
  sp_error (*sp_session_is_scrobbling)(sp_session *, sp_social_provider, sp_scrobbling_state*);
  sp_album * (*sp_toplistbrowse_album)(sp_toplistbrowse *, int);
  sp_linktype (*sp_link_type)(sp_link *);
  int (*sp_search_num_albums)(sp_search *);
  const char * (*sp_build_id)(void);
  sp_link * (*sp_link_create_from_playlist)(sp_playlist *);
  sp_subscribers * (*sp_playlist_subscribers)(sp_playlist *);
  sp_playlist * (*sp_playlistcontainer_playlist)(sp_playlistcontainer *, int);
  sp_error (*sp_session_set_social_credentials)(sp_session *, sp_social_provider, const char*, const char*);
  const char * (*sp_playlist_track_message)(sp_playlist *, int);
  sp_user * (*sp_link_as_user)(sp_link *);
  sp_artist * (*sp_search_artist)(sp_search *, int);
  sp_error (*sp_session_player_seek)(sp_session *, int);
  int (*sp_track_disc)(sp_track *);
  sp_error (*sp_album_release)(sp_album *);
  sp_error (*sp_playlistcontainer_move_playlist)(sp_playlistcontainer *, int, int, bool);
  int (*sp_playlistcontainer_num_playlists)(sp_playlistcontainer *);
  sp_toplistbrowse * (*sp_toplistbrowse_create)(sp_session *, sp_toplisttype, sp_toplistregion, const char *, toplistbrowse_complete_cb *, void *);
  sp_user * (*sp_playlist_track_creator)(sp_playlist *, int);
  bool (*sp_artistbrowse_is_loaded)(sp_artistbrowse *);
  sp_error (*sp_playlist_set_collaborative)(sp_playlist *, bool);
  int (*sp_track_duration)(sp_track *);
  int (*sp_playlist_num_tracks)(sp_playlist *);
  sp_track * (*sp_artistbrowse_tophit_track)(sp_artistbrowse *, int);
  int (*sp_artistbrowse_num_tracks)(sp_artistbrowse *);
  sp_error (*sp_playlist_add_ref)(sp_playlist *);
  sp_error (*sp_playlist_release)(sp_playlist *);
  sp_error (*sp_playlist_set_offline_mode)(sp_session *, sp_playlist *, bool);
  sp_error (*sp_playlistcontainer_add_callbacks)(sp_playlistcontainer *, sp_playlistcontainer_callbacks *, void *);
  const char * (*sp_playlist_name)(sp_playlist *);
  sp_error (*sp_playlist_set_in_ram)(sp_session *, sp_playlist *, bool);
  sp_track * (*sp_link_as_track)(sp_link *);
  int (*sp_offline_time_left)(sp_session *);
  sp_error (*sp_session_set_private_session)(sp_session *, bool);
  int (*sp_session_user_country)(sp_session *);
  sp_error (*sp_session_create)(const sp_session_config *, sp_session **);
  bool (*sp_track_is_autolinked)(sp_session *, sp_track *);
  int (*sp_search_total_artists)(sp_search *);
  sp_error (*sp_inbox_add_ref)(sp_inbox *);
  sp_link * (*sp_link_create_from_track)(sp_track *, int);
  sp_error (*sp_album_add_ref)(sp_album *);
  sp_error (*sp_session_player_play)(sp_session *, bool);
  sp_error (*sp_link_release)(sp_link *);
  const byte * (*sp_album_cover)(sp_album *, sp_image_size);
  sp_error (*sp_playlistcontainer_remove_playlist)(sp_playlistcontainer *, int);
  const byte * (*sp_image_image_id)(sp_image *);
  sp_error (*sp_playlistcontainer_add_folder)(sp_playlistcontainer *, int, const char *);
  sp_error (*sp_session_release)(sp_session *);
  int (*sp_artistbrowse_num_tophit_tracks)(sp_artistbrowse *);
  sp_playlist * (*sp_playlistcontainer_add_playlist)(sp_playlistcontainer *, sp_link *);
  sp_link * (*sp_link_create_from_string)(const char *);
  sp_error (*sp_artist_add_ref)(sp_artist *);
  sp_album * (*sp_link_as_album)(sp_link *);
  sp_link * (*sp_link_create_from_artist)(sp_artist *);
  int (*sp_artistbrowse_backend_request_duration)(sp_artistbrowse *);
  sp_link * (*sp_link_create_from_image)(sp_image *);
  int (*sp_artistbrowse_num_albums)(sp_artistbrowse *);
  int (*sp_track_num_artists)(sp_track *);
  sp_playlist * (*sp_session_inbox_create)(sp_session *);
  sp_albumtype (*sp_album_type)(sp_album *);
  int (*sp_track_index)(sp_track *);
  bool (*sp_track_is_loaded)(sp_track *);
  sp_track * (*sp_track_get_playable)(sp_session *, sp_track *);
  sp_error (*sp_session_relogin)(sp_session *);
  int (*sp_artistbrowse_num_similar_artists)(sp_artistbrowse *);
  sp_playlist * (*sp_playlistcontainer_add_new_playlist)(sp_playlistcontainer *, const char *);
  sp_error (*sp_image_add_load_callback)(sp_image *, image_loaded_cb *, void *);
  bool (*sp_track_is_placeholder)(sp_track *);
  const char * (*sp_search_query)(sp_search *);
  sp_album * (*sp_artistbrowse_album)(sp_artistbrowse *, int);
  const char * (*sp_search_playlist_name)(sp_search *, int);
  sp_link * (*sp_link_create_from_album)(sp_album *);
  sp_error (*sp_track_release)(sp_track *);
  sp_playlistcontainer * (*sp_session_playlistcontainer)(sp_session *);
  sp_error (*sp_artistbrowse_release)(sp_artistbrowse *);
  int (*sp_playlistcontainer_clear_unseen_tracks)(sp_playlistcontainer *, sp_playlist *);
  sp_error (*sp_user_add_ref)(sp_user *);
  bool (*sp_track_is_starred)(sp_session *, sp_track *);
};

static struct libspotify g_libspotify = { .handle = NULL };

void init___(void)
{
  if (g_libspotify.handle == NULL) {
    g_libspotify.handle = dlopen("libspotify.so", RTLD_LAZY);
    *((void **)&g_libspotify.sp_playlist_track) = dlsym(g_libspotify.handle, "sp_playlist_track");
    *((void **)&g_libspotify.sp_artistbrowse_create) = dlsym(g_libspotify.handle, "sp_artistbrowse_create");
    *((void **)&g_libspotify.sp_user_canonical_name) = dlsym(g_libspotify.handle, "sp_user_canonical_name");
    *((void **)&g_libspotify.sp_albumbrowse_review) = dlsym(g_libspotify.handle, "sp_albumbrowse_review");
    *((void **)&g_libspotify.sp_session_set_connection_type) = dlsym(g_libspotify.handle, "sp_session_set_connection_type");
    *((void **)&g_libspotify.sp_playlist_track_seen) = dlsym(g_libspotify.handle, "sp_playlist_track_seen");
    *((void **)&g_libspotify.sp_user_release) = dlsym(g_libspotify.handle, "sp_user_release");
    *((void **)&g_libspotify.sp_offline_sync_get_status) = dlsym(g_libspotify.handle, "sp_offline_sync_get_status");
    *((void **)&g_libspotify.sp_toplistbrowse_backend_request_duration) = dlsym(g_libspotify.handle, "sp_toplistbrowse_backend_request_duration");
    *((void **)&g_libspotify.sp_track_offline_get_status) = dlsym(g_libspotify.handle, "sp_track_offline_get_status");
    *((void **)&g_libspotify.sp_session_publishedcontainer_for_user_create) = dlsym(g_libspotify.handle, "sp_session_publishedcontainer_for_user_create");
    *((void **)&g_libspotify.sp_search_is_loaded) = dlsym(g_libspotify.handle, "sp_search_is_loaded");
    *((void **)&g_libspotify.sp_session_forget_me) = dlsym(g_libspotify.handle, "sp_session_forget_me");
    *((void **)&g_libspotify.sp_link_as_artist) = dlsym(g_libspotify.handle, "sp_link_as_artist");
    *((void **)&g_libspotify.sp_session_set_cache_size) = dlsym(g_libspotify.handle, "sp_session_set_cache_size");
    *((void **)&g_libspotify.sp_playlist_track_create_time) = dlsym(g_libspotify.handle, "sp_playlist_track_create_time");
    *((void **)&g_libspotify.sp_search_num_playlists) = dlsym(g_libspotify.handle, "sp_search_num_playlists");
    *((void **)&g_libspotify.sp_session_process_events) = dlsym(g_libspotify.handle, "sp_session_process_events");
    *((void **)&g_libspotify.sp_session_preferred_bitrate) = dlsym(g_libspotify.handle, "sp_session_preferred_bitrate");
    *((void **)&g_libspotify.sp_artistbrowse_artist) = dlsym(g_libspotify.handle, "sp_artistbrowse_artist");
    *((void **)&g_libspotify.sp_image_create) = dlsym(g_libspotify.handle, "sp_image_create");
    *((void **)&g_libspotify.sp_playlistcontainer_add_ref) = dlsym(g_libspotify.handle, "sp_playlistcontainer_add_ref");
    *((void **)&g_libspotify.sp_search_release) = dlsym(g_libspotify.handle, "sp_search_release");
    *((void **)&g_libspotify.sp_playlistcontainer_release) = dlsym(g_libspotify.handle, "sp_playlistcontainer_release");
    *((void **)&g_libspotify.sp_albumbrowse_create) = dlsym(g_libspotify.handle, "sp_albumbrowse_create");
    *((void **)&g_libspotify.sp_session_logout) = dlsym(g_libspotify.handle, "sp_session_logout");
    *((void **)&g_libspotify.sp_playlist_remove_tracks) = dlsym(g_libspotify.handle, "sp_playlist_remove_tracks");
    *((void **)&g_libspotify.sp_playlistcontainer_is_loaded) = dlsym(g_libspotify.handle, "sp_playlistcontainer_is_loaded");
    *((void **)&g_libspotify.sp_session_is_scrobbling_possible) = dlsym(g_libspotify.handle, "sp_session_is_scrobbling_possible");
    *((void **)&g_libspotify.sp_artistbrowse_error) = dlsym(g_libspotify.handle, "sp_artistbrowse_error");
    *((void **)&g_libspotify.sp_toplistbrowse_is_loaded) = dlsym(g_libspotify.handle, "sp_toplistbrowse_is_loaded");
    *((void **)&g_libspotify.sp_image_remove_load_callback) = dlsym(g_libspotify.handle, "sp_image_remove_load_callback");
    *((void **)&g_libspotify.sp_link_as_string) = dlsym(g_libspotify.handle, "sp_link_as_string");
    *((void **)&g_libspotify.sp_playlist_add_tracks) = dlsym(g_libspotify.handle, "sp_playlist_add_tracks");
    *((void **)&g_libspotify.sp_playlist_is_in_ram) = dlsym(g_libspotify.handle, "sp_playlist_is_in_ram");
    *((void **)&g_libspotify.sp_artistbrowse_biography) = dlsym(g_libspotify.handle, "sp_artistbrowse_biography");
    *((void **)&g_libspotify.sp_error_message) = dlsym(g_libspotify.handle, "sp_error_message");
    *((void **)&g_libspotify.sp_session_set_scrobbling) = dlsym(g_libspotify.handle, "sp_session_set_scrobbling");
    *((void **)&g_libspotify.sp_playlist_get_description) = dlsym(g_libspotify.handle, "sp_playlist_get_description");
    *((void **)&g_libspotify.sp_album_name) = dlsym(g_libspotify.handle, "sp_album_name");
    *((void **)&g_libspotify.sp_search_total_albums) = dlsym(g_libspotify.handle, "sp_search_total_albums");
    *((void **)&g_libspotify.sp_albumbrowse_artist) = dlsym(g_libspotify.handle, "sp_albumbrowse_artist");
    *((void **)&g_libspotify.sp_session_starred_for_user_create) = dlsym(g_libspotify.handle, "sp_session_starred_for_user_create");
    *((void **)&g_libspotify.sp_albumbrowse_num_copyrights) = dlsym(g_libspotify.handle, "sp_albumbrowse_num_copyrights");
    *((void **)&g_libspotify.sp_link_create_from_artistbrowse_portrait) = dlsym(g_libspotify.handle, "sp_link_create_from_artistbrowse_portrait");
    *((void **)&g_libspotify.sp_link_add_ref) = dlsym(g_libspotify.handle, "sp_link_add_ref");
    *((void **)&g_libspotify.sp_session_login) = dlsym(g_libspotify.handle, "sp_session_login");
    *((void **)&g_libspotify.sp_toplistbrowse_error) = dlsym(g_libspotify.handle, "sp_toplistbrowse_error");
    *((void **)&g_libspotify.sp_track_error) = dlsym(g_libspotify.handle, "sp_track_error");
    *((void **)&g_libspotify.sp_playlist_add_callbacks) = dlsym(g_libspotify.handle, "sp_playlist_add_callbacks");
    *((void **)&g_libspotify.sp_search_playlist_uri) = dlsym(g_libspotify.handle, "sp_search_playlist_uri");
    *((void **)&g_libspotify.sp_session_player_load) = dlsym(g_libspotify.handle, "sp_session_player_load");
    *((void **)&g_libspotify.sp_session_starred_create) = dlsym(g_libspotify.handle, "sp_session_starred_create");
    *((void **)&g_libspotify.sp_user_is_loaded) = dlsym(g_libspotify.handle, "sp_user_is_loaded");
    *((void **)&g_libspotify.sp_track_get_availability) = dlsym(g_libspotify.handle, "sp_track_get_availability");
    *((void **)&g_libspotify.sp_session_player_unload) = dlsym(g_libspotify.handle, "sp_session_player_unload");
    *((void **)&g_libspotify.sp_search_create) = dlsym(g_libspotify.handle, "sp_search_create");
    *((void **)&g_libspotify.sp_session_user_name) = dlsym(g_libspotify.handle, "sp_session_user_name");
    *((void **)&g_libspotify.sp_playlist_set_autolink_tracks) = dlsym(g_libspotify.handle, "sp_playlist_set_autolink_tracks");
    *((void **)&g_libspotify.sp_link_create_from_search) = dlsym(g_libspotify.handle, "sp_link_create_from_search");
    *((void **)&g_libspotify.sp_session_preferred_offline_bitrate) = dlsym(g_libspotify.handle, "sp_session_preferred_offline_bitrate");
    *((void **)&g_libspotify.sp_playlistcontainer_playlist_folder_name) = dlsym(g_libspotify.handle, "sp_playlistcontainer_playlist_folder_name");
    *((void **)&g_libspotify.sp_albumbrowse_album) = dlsym(g_libspotify.handle, "sp_albumbrowse_album");
    *((void **)&g_libspotify.sp_toplistbrowse_track) = dlsym(g_libspotify.handle, "sp_toplistbrowse_track");
    *((void **)&g_libspotify.sp_session_get_volume_normalization) = dlsym(g_libspotify.handle, "sp_session_get_volume_normalization");
    *((void **)&g_libspotify.sp_search_num_tracks) = dlsym(g_libspotify.handle, "sp_search_num_tracks");
    *((void **)&g_libspotify.sp_playlistcontainer_get_unseen_tracks) = dlsym(g_libspotify.handle, "sp_playlistcontainer_get_unseen_tracks");
    *((void **)&g_libspotify.sp_artistbrowse_portrait) = dlsym(g_libspotify.handle, "sp_artistbrowse_portrait");
    *((void **)&g_libspotify.sp_search_total_tracks) = dlsym(g_libspotify.handle, "sp_search_total_tracks");
    *((void **)&g_libspotify.sp_artistbrowse_add_ref) = dlsym(g_libspotify.handle, "sp_artistbrowse_add_ref");
    *((void **)&g_libspotify.sp_search_add_ref) = dlsym(g_libspotify.handle, "sp_search_add_ref");
    *((void **)&g_libspotify.sp_search_error) = dlsym(g_libspotify.handle, "sp_search_error");
    *((void **)&g_libspotify.sp_toplistbrowse_release) = dlsym(g_libspotify.handle, "sp_toplistbrowse_release");
    *((void **)&g_libspotify.sp_toplistbrowse_artist) = dlsym(g_libspotify.handle, "sp_toplistbrowse_artist");
    *((void **)&g_libspotify.sp_image_add_ref) = dlsym(g_libspotify.handle, "sp_image_add_ref");
    *((void **)&g_libspotify.sp_playlist_update_subscribers) = dlsym(g_libspotify.handle, "sp_playlist_update_subscribers");
    *((void **)&g_libspotify.sp_playlistcontainer_playlist_type) = dlsym(g_libspotify.handle, "sp_playlistcontainer_playlist_type");
    *((void **)&g_libspotify.sp_toplistbrowse_num_albums) = dlsym(g_libspotify.handle, "sp_toplistbrowse_num_albums");
    *((void **)&g_libspotify.sp_session_flush_caches) = dlsym(g_libspotify.handle, "sp_session_flush_caches");
    *((void **)&g_libspotify.sp_playlist_track_set_seen) = dlsym(g_libspotify.handle, "sp_playlist_track_set_seen");
    *((void **)&g_libspotify.sp_image_error) = dlsym(g_libspotify.handle, "sp_image_error");
    *((void **)&g_libspotify.sp_image_release) = dlsym(g_libspotify.handle, "sp_image_release");
    *((void **)&g_libspotify.sp_playlist_create) = dlsym(g_libspotify.handle, "sp_playlist_create");
    *((void **)&g_libspotify.sp_playlist_get_offline_status) = dlsym(g_libspotify.handle, "sp_playlist_get_offline_status");
    *((void **)&g_libspotify.sp_artistbrowse_num_portraits) = dlsym(g_libspotify.handle, "sp_artistbrowse_num_portraits");
    *((void **)&g_libspotify.sp_search_playlist) = dlsym(g_libspotify.handle, "sp_search_playlist");
    *((void **)&g_libspotify.sp_track_popularity) = dlsym(g_libspotify.handle, "sp_track_popularity");
    *((void **)&g_libspotify.sp_inbox_release) = dlsym(g_libspotify.handle, "sp_inbox_release");
    *((void **)&g_libspotify.sp_session_user) = dlsym(g_libspotify.handle, "sp_session_user");
    *((void **)&g_libspotify.sp_albumbrowse_error) = dlsym(g_libspotify.handle, "sp_albumbrowse_error");
    *((void **)&g_libspotify.sp_inbox_error) = dlsym(g_libspotify.handle, "sp_inbox_error");
    *((void **)&g_libspotify.sp_artistbrowse_track) = dlsym(g_libspotify.handle, "sp_artistbrowse_track");
    *((void **)&g_libspotify.sp_albumbrowse_add_ref) = dlsym(g_libspotify.handle, "sp_albumbrowse_add_ref");
    *((void **)&g_libspotify.sp_playlistcontainer_owner) = dlsym(g_libspotify.handle, "sp_playlistcontainer_owner");
    *((void **)&g_libspotify.sp_album_is_available) = dlsym(g_libspotify.handle, "sp_album_is_available");
    *((void **)&g_libspotify.sp_toplistbrowse_num_artists) = dlsym(g_libspotify.handle, "sp_toplistbrowse_num_artists");
    *((void **)&g_libspotify.sp_session_userdata) = dlsym(g_libspotify.handle, "sp_session_userdata");
    *((void **)&g_libspotify.sp_albumbrowse_release) = dlsym(g_libspotify.handle, "sp_albumbrowse_release");
    *((void **)&g_libspotify.sp_toplistbrowse_num_tracks) = dlsym(g_libspotify.handle, "sp_toplistbrowse_num_tracks");
    *((void **)&g_libspotify.sp_playlist_owner) = dlsym(g_libspotify.handle, "sp_playlist_owner");
    *((void **)&g_libspotify.sp_inbox_post_tracks) = dlsym(g_libspotify.handle, "sp_inbox_post_tracks");
    *((void **)&g_libspotify.sp_playlistcontainer_playlist_folder_id) = dlsym(g_libspotify.handle, "sp_playlistcontainer_playlist_folder_id");
    *((void **)&g_libspotify.sp_track_add_ref) = dlsym(g_libspotify.handle, "sp_track_add_ref");
    *((void **)&g_libspotify.sp_link_create_from_user) = dlsym(g_libspotify.handle, "sp_link_create_from_user");
    *((void **)&g_libspotify.sp_playlist_is_collaborative) = dlsym(g_libspotify.handle, "sp_playlist_is_collaborative");
    *((void **)&g_libspotify.sp_image_format) = dlsym(g_libspotify.handle, "sp_image_format");
    *((void **)&g_libspotify.sp_search_num_artists) = dlsym(g_libspotify.handle, "sp_search_num_artists");
    *((void **)&g_libspotify.sp_image_data) = dlsym(g_libspotify.handle, "sp_image_data");
    *((void **)&g_libspotify.sp_localtrack_create) = dlsym(g_libspotify.handle, "sp_localtrack_create");
    *((void **)&g_libspotify.sp_albumbrowse_copyright) = dlsym(g_libspotify.handle, "sp_albumbrowse_copyright");
    *((void **)&g_libspotify.sp_search_album) = dlsym(g_libspotify.handle, "sp_search_album");
    *((void **)&g_libspotify.sp_session_set_connection_rules) = dlsym(g_libspotify.handle, "sp_session_set_connection_rules");
    *((void **)&g_libspotify.sp_offline_num_playlists) = dlsym(g_libspotify.handle, "sp_offline_num_playlists");
    *((void **)&g_libspotify.sp_track_album) = dlsym(g_libspotify.handle, "sp_track_album");
    *((void **)&g_libspotify.sp_track_name) = dlsym(g_libspotify.handle, "sp_track_name");
    *((void **)&g_libspotify.sp_search_total_playlists) = dlsym(g_libspotify.handle, "sp_search_total_playlists");
    *((void **)&g_libspotify.sp_playlist_reorder_tracks) = dlsym(g_libspotify.handle, "sp_playlist_reorder_tracks");
    *((void **)&g_libspotify.sp_session_set_volume_normalization) = dlsym(g_libspotify.handle, "sp_session_set_volume_normalization");
    *((void **)&g_libspotify.sp_track_set_starred) = dlsym(g_libspotify.handle, "sp_track_set_starred");
    *((void **)&g_libspotify.sp_artist_is_loaded) = dlsym(g_libspotify.handle, "sp_artist_is_loaded");
    *((void **)&g_libspotify.sp_albumbrowse_track) = dlsym(g_libspotify.handle, "sp_albumbrowse_track");
    *((void **)&g_libspotify.sp_link_as_track_and_offset) = dlsym(g_libspotify.handle, "sp_link_as_track_and_offset");
    *((void **)&g_libspotify.sp_artistbrowse_similar_artist) = dlsym(g_libspotify.handle, "sp_artistbrowse_similar_artist");
    *((void **)&g_libspotify.sp_session_connectionstate) = dlsym(g_libspotify.handle, "sp_session_connectionstate");
    *((void **)&g_libspotify.sp_playlist_get_offline_download_completed) = dlsym(g_libspotify.handle, "sp_playlist_get_offline_download_completed");
    *((void **)&g_libspotify.sp_playlist_remove_callbacks) = dlsym(g_libspotify.handle, "sp_playlist_remove_callbacks");
    *((void **)&g_libspotify.sp_image_is_loaded) = dlsym(g_libspotify.handle, "sp_image_is_loaded");
    *((void **)&g_libspotify.sp_playlistcontainer_remove_callbacks) = dlsym(g_libspotify.handle, "sp_playlistcontainer_remove_callbacks");
    *((void **)&g_libspotify.sp_albumbrowse_backend_request_duration) = dlsym(g_libspotify.handle, "sp_albumbrowse_backend_request_duration");
    *((void **)&g_libspotify.sp_playlist_subscribers_free) = dlsym(g_libspotify.handle, "sp_playlist_subscribers_free");
    *((void **)&g_libspotify.sp_search_playlist_image_uri) = dlsym(g_libspotify.handle, "sp_search_playlist_image_uri");
    *((void **)&g_libspotify.sp_track_artist) = dlsym(g_libspotify.handle, "sp_track_artist");
    *((void **)&g_libspotify.sp_session_is_private_session) = dlsym(g_libspotify.handle, "sp_session_is_private_session");
    *((void **)&g_libspotify.sp_albumbrowse_num_tracks) = dlsym(g_libspotify.handle, "sp_albumbrowse_num_tracks");
    *((void **)&g_libspotify.sp_session_remembered_user) = dlsym(g_libspotify.handle, "sp_session_remembered_user");
    *((void **)&g_libspotify.sp_playlist_num_subscribers) = dlsym(g_libspotify.handle, "sp_playlist_num_subscribers");
    *((void **)&g_libspotify.sp_user_display_name) = dlsym(g_libspotify.handle, "sp_user_display_name");
    *((void **)&g_libspotify.sp_toplistbrowse_add_ref) = dlsym(g_libspotify.handle, "sp_toplistbrowse_add_ref");
    *((void **)&g_libspotify.sp_playlist_is_loaded) = dlsym(g_libspotify.handle, "sp_playlist_is_loaded");
    *((void **)&g_libspotify.sp_playlist_get_image) = dlsym(g_libspotify.handle, "sp_playlist_get_image");
    *((void **)&g_libspotify.sp_image_create_from_link) = dlsym(g_libspotify.handle, "sp_image_create_from_link");
    *((void **)&g_libspotify.sp_album_year) = dlsym(g_libspotify.handle, "sp_album_year");
    *((void **)&g_libspotify.sp_search_track) = dlsym(g_libspotify.handle, "sp_search_track");
    *((void **)&g_libspotify.sp_albumbrowse_is_loaded) = dlsym(g_libspotify.handle, "sp_albumbrowse_is_loaded");
    *((void **)&g_libspotify.sp_link_create_from_artist_portrait) = dlsym(g_libspotify.handle, "sp_link_create_from_artist_portrait");
    *((void **)&g_libspotify.sp_album_artist) = dlsym(g_libspotify.handle, "sp_album_artist");
    *((void **)&g_libspotify.sp_offline_tracks_to_sync) = dlsym(g_libspotify.handle, "sp_offline_tracks_to_sync");
    *((void **)&g_libspotify.sp_session_player_prefetch) = dlsym(g_libspotify.handle, "sp_session_player_prefetch");
    *((void **)&g_libspotify.sp_playlist_rename) = dlsym(g_libspotify.handle, "sp_playlist_rename");
    *((void **)&g_libspotify.sp_artist_release) = dlsym(g_libspotify.handle, "sp_artist_release");
    *((void **)&g_libspotify.sp_artist_name) = dlsym(g_libspotify.handle, "sp_artist_name");
    *((void **)&g_libspotify.sp_playlist_has_pending_changes) = dlsym(g_libspotify.handle, "sp_playlist_has_pending_changes");
    *((void **)&g_libspotify.sp_track_is_local) = dlsym(g_libspotify.handle, "sp_track_is_local");
    *((void **)&g_libspotify.sp_album_is_loaded) = dlsym(g_libspotify.handle, "sp_album_is_loaded");
    *((void **)&g_libspotify.sp_link_create_from_album_cover) = dlsym(g_libspotify.handle, "sp_link_create_from_album_cover");
    *((void **)&g_libspotify.sp_search_did_you_mean) = dlsym(g_libspotify.handle, "sp_search_did_you_mean");
    *((void **)&g_libspotify.sp_artist_portrait) = dlsym(g_libspotify.handle, "sp_artist_portrait");
    *((void **)&g_libspotify.sp_session_is_scrobbling) = dlsym(g_libspotify.handle, "sp_session_is_scrobbling");
    *((void **)&g_libspotify.sp_toplistbrowse_album) = dlsym(g_libspotify.handle, "sp_toplistbrowse_album");
    *((void **)&g_libspotify.sp_link_type) = dlsym(g_libspotify.handle, "sp_link_type");
    *((void **)&g_libspotify.sp_search_num_albums) = dlsym(g_libspotify.handle, "sp_search_num_albums");
    *((void **)&g_libspotify.sp_build_id) = dlsym(g_libspotify.handle, "sp_build_id");
    *((void **)&g_libspotify.sp_link_create_from_playlist) = dlsym(g_libspotify.handle, "sp_link_create_from_playlist");
    *((void **)&g_libspotify.sp_playlist_subscribers) = dlsym(g_libspotify.handle, "sp_playlist_subscribers");
    *((void **)&g_libspotify.sp_playlistcontainer_playlist) = dlsym(g_libspotify.handle, "sp_playlistcontainer_playlist");
    *((void **)&g_libspotify.sp_session_set_social_credentials) = dlsym(g_libspotify.handle, "sp_session_set_social_credentials");
    *((void **)&g_libspotify.sp_playlist_track_message) = dlsym(g_libspotify.handle, "sp_playlist_track_message");
    *((void **)&g_libspotify.sp_link_as_user) = dlsym(g_libspotify.handle, "sp_link_as_user");
    *((void **)&g_libspotify.sp_search_artist) = dlsym(g_libspotify.handle, "sp_search_artist");
    *((void **)&g_libspotify.sp_session_player_seek) = dlsym(g_libspotify.handle, "sp_session_player_seek");
    *((void **)&g_libspotify.sp_track_disc) = dlsym(g_libspotify.handle, "sp_track_disc");
    *((void **)&g_libspotify.sp_album_release) = dlsym(g_libspotify.handle, "sp_album_release");
    *((void **)&g_libspotify.sp_playlistcontainer_move_playlist) = dlsym(g_libspotify.handle, "sp_playlistcontainer_move_playlist");
    *((void **)&g_libspotify.sp_playlistcontainer_num_playlists) = dlsym(g_libspotify.handle, "sp_playlistcontainer_num_playlists");
    *((void **)&g_libspotify.sp_toplistbrowse_create) = dlsym(g_libspotify.handle, "sp_toplistbrowse_create");
    *((void **)&g_libspotify.sp_playlist_track_creator) = dlsym(g_libspotify.handle, "sp_playlist_track_creator");
    *((void **)&g_libspotify.sp_artistbrowse_is_loaded) = dlsym(g_libspotify.handle, "sp_artistbrowse_is_loaded");
    *((void **)&g_libspotify.sp_playlist_set_collaborative) = dlsym(g_libspotify.handle, "sp_playlist_set_collaborative");
    *((void **)&g_libspotify.sp_track_duration) = dlsym(g_libspotify.handle, "sp_track_duration");
    *((void **)&g_libspotify.sp_playlist_num_tracks) = dlsym(g_libspotify.handle, "sp_playlist_num_tracks");
    *((void **)&g_libspotify.sp_artistbrowse_tophit_track) = dlsym(g_libspotify.handle, "sp_artistbrowse_tophit_track");
    *((void **)&g_libspotify.sp_artistbrowse_num_tracks) = dlsym(g_libspotify.handle, "sp_artistbrowse_num_tracks");
    *((void **)&g_libspotify.sp_playlist_add_ref) = dlsym(g_libspotify.handle, "sp_playlist_add_ref");
    *((void **)&g_libspotify.sp_playlist_release) = dlsym(g_libspotify.handle, "sp_playlist_release");
    *((void **)&g_libspotify.sp_playlist_set_offline_mode) = dlsym(g_libspotify.handle, "sp_playlist_set_offline_mode");
    *((void **)&g_libspotify.sp_playlistcontainer_add_callbacks) = dlsym(g_libspotify.handle, "sp_playlistcontainer_add_callbacks");
    *((void **)&g_libspotify.sp_playlist_name) = dlsym(g_libspotify.handle, "sp_playlist_name");
    *((void **)&g_libspotify.sp_playlist_set_in_ram) = dlsym(g_libspotify.handle, "sp_playlist_set_in_ram");
    *((void **)&g_libspotify.sp_link_as_track) = dlsym(g_libspotify.handle, "sp_link_as_track");
    *((void **)&g_libspotify.sp_offline_time_left) = dlsym(g_libspotify.handle, "sp_offline_time_left");
    *((void **)&g_libspotify.sp_session_set_private_session) = dlsym(g_libspotify.handle, "sp_session_set_private_session");
    *((void **)&g_libspotify.sp_session_user_country) = dlsym(g_libspotify.handle, "sp_session_user_country");
    *((void **)&g_libspotify.sp_session_create) = dlsym(g_libspotify.handle, "sp_session_create");
    *((void **)&g_libspotify.sp_track_is_autolinked) = dlsym(g_libspotify.handle, "sp_track_is_autolinked");
    *((void **)&g_libspotify.sp_search_total_artists) = dlsym(g_libspotify.handle, "sp_search_total_artists");
    *((void **)&g_libspotify.sp_inbox_add_ref) = dlsym(g_libspotify.handle, "sp_inbox_add_ref");
    *((void **)&g_libspotify.sp_link_create_from_track) = dlsym(g_libspotify.handle, "sp_link_create_from_track");
    *((void **)&g_libspotify.sp_album_add_ref) = dlsym(g_libspotify.handle, "sp_album_add_ref");
    *((void **)&g_libspotify.sp_session_player_play) = dlsym(g_libspotify.handle, "sp_session_player_play");
    *((void **)&g_libspotify.sp_link_release) = dlsym(g_libspotify.handle, "sp_link_release");
    *((void **)&g_libspotify.sp_album_cover) = dlsym(g_libspotify.handle, "sp_album_cover");
    *((void **)&g_libspotify.sp_playlistcontainer_remove_playlist) = dlsym(g_libspotify.handle, "sp_playlistcontainer_remove_playlist");
    *((void **)&g_libspotify.sp_image_image_id) = dlsym(g_libspotify.handle, "sp_image_image_id");
    *((void **)&g_libspotify.sp_playlistcontainer_add_folder) = dlsym(g_libspotify.handle, "sp_playlistcontainer_add_folder");
    *((void **)&g_libspotify.sp_session_release) = dlsym(g_libspotify.handle, "sp_session_release");
    *((void **)&g_libspotify.sp_artistbrowse_num_tophit_tracks) = dlsym(g_libspotify.handle, "sp_artistbrowse_num_tophit_tracks");
    *((void **)&g_libspotify.sp_playlistcontainer_add_playlist) = dlsym(g_libspotify.handle, "sp_playlistcontainer_add_playlist");
    *((void **)&g_libspotify.sp_link_create_from_string) = dlsym(g_libspotify.handle, "sp_link_create_from_string");
    *((void **)&g_libspotify.sp_artist_add_ref) = dlsym(g_libspotify.handle, "sp_artist_add_ref");
    *((void **)&g_libspotify.sp_link_as_album) = dlsym(g_libspotify.handle, "sp_link_as_album");
    *((void **)&g_libspotify.sp_link_create_from_artist) = dlsym(g_libspotify.handle, "sp_link_create_from_artist");
    *((void **)&g_libspotify.sp_artistbrowse_backend_request_duration) = dlsym(g_libspotify.handle, "sp_artistbrowse_backend_request_duration");
    *((void **)&g_libspotify.sp_link_create_from_image) = dlsym(g_libspotify.handle, "sp_link_create_from_image");
    *((void **)&g_libspotify.sp_artistbrowse_num_albums) = dlsym(g_libspotify.handle, "sp_artistbrowse_num_albums");
    *((void **)&g_libspotify.sp_track_num_artists) = dlsym(g_libspotify.handle, "sp_track_num_artists");
    *((void **)&g_libspotify.sp_session_inbox_create) = dlsym(g_libspotify.handle, "sp_session_inbox_create");
    *((void **)&g_libspotify.sp_album_type) = dlsym(g_libspotify.handle, "sp_album_type");
    *((void **)&g_libspotify.sp_track_index) = dlsym(g_libspotify.handle, "sp_track_index");
    *((void **)&g_libspotify.sp_track_is_loaded) = dlsym(g_libspotify.handle, "sp_track_is_loaded");
    *((void **)&g_libspotify.sp_track_get_playable) = dlsym(g_libspotify.handle, "sp_track_get_playable");
    *((void **)&g_libspotify.sp_session_relogin) = dlsym(g_libspotify.handle, "sp_session_relogin");
    *((void **)&g_libspotify.sp_artistbrowse_num_similar_artists) = dlsym(g_libspotify.handle, "sp_artistbrowse_num_similar_artists");
    *((void **)&g_libspotify.sp_playlistcontainer_add_new_playlist) = dlsym(g_libspotify.handle, "sp_playlistcontainer_add_new_playlist");
    *((void **)&g_libspotify.sp_image_add_load_callback) = dlsym(g_libspotify.handle, "sp_image_add_load_callback");
    *((void **)&g_libspotify.sp_track_is_placeholder) = dlsym(g_libspotify.handle, "sp_track_is_placeholder");
    *((void **)&g_libspotify.sp_search_query) = dlsym(g_libspotify.handle, "sp_search_query");
    *((void **)&g_libspotify.sp_artistbrowse_album) = dlsym(g_libspotify.handle, "sp_artistbrowse_album");
    *((void **)&g_libspotify.sp_search_playlist_name) = dlsym(g_libspotify.handle, "sp_search_playlist_name");
    *((void **)&g_libspotify.sp_link_create_from_album) = dlsym(g_libspotify.handle, "sp_link_create_from_album");
    *((void **)&g_libspotify.sp_track_release) = dlsym(g_libspotify.handle, "sp_track_release");
    *((void **)&g_libspotify.sp_session_playlistcontainer) = dlsym(g_libspotify.handle, "sp_session_playlistcontainer");
    *((void **)&g_libspotify.sp_artistbrowse_release) = dlsym(g_libspotify.handle, "sp_artistbrowse_release");
    *((void **)&g_libspotify.sp_playlistcontainer_clear_unseen_tracks) = dlsym(g_libspotify.handle, "sp_playlistcontainer_clear_unseen_tracks");
    *((void **)&g_libspotify.sp_user_add_ref) = dlsym(g_libspotify.handle, "sp_user_add_ref");
    *((void **)&g_libspotify.sp_track_is_starred) = dlsym(g_libspotify.handle, "sp_track_is_starred");
    }

}

